name: 
    BiocBook
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - fastqc 
    - fastqc 
    - trim-galore 
    - bowtie2 
    - deepTools 
    - macs2 
    - meme 
    - subread 
    - star 
    - samtools 
    - bedtools 
    - pandas 
    - numpy 
    - pandas 
    - matplotlib 
    - cooler 
    - cooltools 
    - hicstuff 
    - chromosight
